//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_DIST_PROFILE
    {
        public ADM_DIST_PROFILE()
        {
            this.ADM_ENTITY_TYPE_ACCESS = new HashSet<ADM_ENTITY_TYPE_ACCESS>();
            this.ADM_USER_DIST = new HashSet<ADM_USER_DIST>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public decimal EFFICENCY_FACTOR { get; set; }
        public System.DateTime EFFECTIVE_DATETIME { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<ADM_ENTITY_TYPE_ACCESS> ADM_ENTITY_TYPE_ACCESS { get; set; }
        public virtual ICollection<ADM_USER_DIST> ADM_USER_DIST { get; set; }
    }
}
