//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_NOTE_TYPE
    {
        public ADM_NOTE_TYPE()
        {
            this.ADM_NOTE_TYPE_LOCALIZED = new HashSet<ADM_NOTE_TYPE_LOCALIZED>();
            this.PRC_NOTE = new HashSet<PRC_NOTE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public System.DateTime EFFECTIVE_DATETIME { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<ADM_NOTE_TYPE_LOCALIZED> ADM_NOTE_TYPE_LOCALIZED { get; set; }
        public virtual ICollection<PRC_NOTE> PRC_NOTE { get; set; }
    }
}
