//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_TEMPLATE_ACTION
    {
        public ADM_TEMPLATE_ACTION()
        {
            this.ADM_TEMPLATE_ATTACHMENT = new HashSet<ADM_TEMPLATE_ATTACHMENT>();
            this.ADM_TEMPLATE_LINK = new HashSet<ADM_TEMPLATE_LINK>();
            this.ADM_TEMPLATE_REMINDER = new HashSet<ADM_TEMPLATE_REMINDER>();
            this.ADM_TEMPLATE_ACTION1 = new HashSet<ADM_TEMPLATE_ACTION>();
        }
    
        public int ID { get; set; }
        public string DESCRIPTION { get; set; }
        public short SEQUENCE { get; set; }
        public int ACTIVITY_TYPE_ID { get; set; }
        public Nullable<int> PARENT_TEMPLATE_ACTION_ID { get; set; }
        public int GENERATED_ACTION_TYPE_ID { get; set; }
        public short STATIC_ACTION { get; set; }
        public short PARENT_WORK_STATUS { get; set; }
        public Nullable<int> INCLUSION_RULE_ID { get; set; }
        public int ORG_LEVEL_ID { get; set; }
        public short PLATFORM_TO_APPLY { get; set; }
        public System.DateTime EFFECTIVE_DATETIME { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_ACTION_TYPE ADM_ACTION_TYPE { get; set; }
        public virtual ADM_ACTIVITY_TYPE ADM_ACTIVITY_TYPE { get; set; }
        public virtual ADM_ORG_LEVEL ADM_ORG_LEVEL { get; set; }
        public virtual ADM_RULE ADM_RULE { get; set; }
        public virtual ICollection<ADM_TEMPLATE_ATTACHMENT> ADM_TEMPLATE_ATTACHMENT { get; set; }
        public virtual ICollection<ADM_TEMPLATE_LINK> ADM_TEMPLATE_LINK { get; set; }
        public virtual ICollection<ADM_TEMPLATE_REMINDER> ADM_TEMPLATE_REMINDER { get; set; }
        public virtual ICollection<ADM_TEMPLATE_ACTION> ADM_TEMPLATE_ACTION1 { get; set; }
        public virtual ADM_TEMPLATE_ACTION ADM_TEMPLATE_ACTION2 { get; set; }
    }
}
