//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_CONTENT
    {
        public ADM_CONTENT()
        {
            this.PRC_ATTACHMENT = new HashSet<PRC_ATTACHMENT>();
            this.PRC_ATTACHMENT_REFERENCE = new HashSet<PRC_ATTACHMENT_REFERENCE>();
        }
    
        public int ID { get; set; }
        public int CONTENT_TYPE_ID { get; set; }
        public string NAME { get; set; }
        public byte[] CONTENT { get; set; }
        public string FILE_NAME { get; set; }
        public byte[] VIEWER_PPC { get; set; }
        public byte[] VIEWER_WIN { get; set; }
        public byte[] XSL_TO_MBM { get; set; }
        public byte[] XSL_FROM_MBM { get; set; }
        public byte[] XSL_TO_OUTPUT { get; set; }
        public System.DateTime EFFECTIVE_DATETIME { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_CONTENT_TYPE ADM_CONTENT_TYPE { get; set; }
        public virtual ICollection<PRC_ATTACHMENT> PRC_ATTACHMENT { get; set; }
        public virtual ICollection<PRC_ATTACHMENT_REFERENCE> PRC_ATTACHMENT_REFERENCE { get; set; }
    }
}
