//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_WEB_CONFIG
    {
        public int ID { get; set; }
        public short APP_ID { get; set; }
        public int AUTHORITY_TYPE_ID { get; set; }
        public string TAG_CODE { get; set; }
        public string VALUE { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_AUTHORITY_TYPE ADM_AUTHORITY_TYPE { get; set; }
        public virtual SYS_WEB_CONFIG SYS_WEB_CONFIG { get; set; }
    }
}
