//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_ACTIVITY_TYPE
    {
        public ADM_ACTIVITY_TYPE()
        {
            this.AUX_CASE_TYPE = new HashSet<AUX_CASE_TYPE>();
            this.AUX_SURGERY_TYPE = new HashSet<AUX_SURGERY_TYPE>();
            this.ADM_ACTIVITY_TYPE_LOCALIZED = new HashSet<ADM_ACTIVITY_TYPE_LOCALIZED>();
            this.ADM_TEMPLATE_ACTION = new HashSet<ADM_TEMPLATE_ACTION>();
            this.ADM_TEMPLATE_ACTIVITY = new HashSet<ADM_TEMPLATE_ACTIVITY>();
            this.ADM_TEMPLATE_ACTIVITY1 = new HashSet<ADM_TEMPLATE_ACTIVITY>();
            this.ADM_TEMPLATE_ATTACHMENT = new HashSet<ADM_TEMPLATE_ATTACHMENT>();
            this.ADM_TEMPLATE_LINK = new HashSet<ADM_TEMPLATE_LINK>();
            this.ADM_TEMPLATE_REMINDER = new HashSet<ADM_TEMPLATE_REMINDER>();
            this.AUX_ACTIVITY_TYPE_CAP_CLASS = new HashSet<AUX_ACTIVITY_TYPE_CAP_CLASS>();
            this.AUX_KIT_TEMPLATE = new HashSet<AUX_KIT_TEMPLATE>();
            this.PRC_ACTIVITY = new HashSet<PRC_ACTIVITY>();
            this.PRC_RECURRENCE_ACTIVITY = new HashSet<PRC_RECURRENCE_ACTIVITY>();
            this.AUX_CAP_CODE = new HashSet<AUX_CAP_CODE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LOB_ID { get; set; }
        public string NAME { get; set; }
        public short CATEGORY { get; set; }
        public string DESCRIPTION { get; set; }
        public string SYS_CODE { get; set; }
        public double DURATION { get; set; }
        public short DISTRIBUTION_PARENT_OVERRIDE { get; set; }
        public int WEIGHT { get; set; }
        public Nullable<double> AGING_DURATION { get; set; }
        public short RETENTION_DURATION { get; set; }
        public string CUSTOM_FIELD_1_CONFIG { get; set; }
        public string CUSTOM_FIELD_2_CONFIG { get; set; }
        public string CUSTOM_FIELD_3_CONFIG { get; set; }
        public string CUSTOM_FIELD_4_CONFIG { get; set; }
        public string CUSTOM_FIELD_5_CONFIG { get; set; }
        public string CUSTOM_FIELD_6_CONFIG { get; set; }
        public string CUSTOM_FIELD_7_CONFIG { get; set; }
        public string CUSTOM_FIELD_8_CONFIG { get; set; }
        public System.DateTime EFFECTIVE_DATETIME { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<AUX_CASE_TYPE> AUX_CASE_TYPE { get; set; }
        public virtual ICollection<AUX_SURGERY_TYPE> AUX_SURGERY_TYPE { get; set; }
        public virtual SYS_LOB SYS_LOB { get; set; }
        public virtual ICollection<ADM_ACTIVITY_TYPE_LOCALIZED> ADM_ACTIVITY_TYPE_LOCALIZED { get; set; }
        public virtual ICollection<ADM_TEMPLATE_ACTION> ADM_TEMPLATE_ACTION { get; set; }
        public virtual ICollection<ADM_TEMPLATE_ACTIVITY> ADM_TEMPLATE_ACTIVITY { get; set; }
        public virtual ICollection<ADM_TEMPLATE_ACTIVITY> ADM_TEMPLATE_ACTIVITY1 { get; set; }
        public virtual ICollection<ADM_TEMPLATE_ATTACHMENT> ADM_TEMPLATE_ATTACHMENT { get; set; }
        public virtual ICollection<ADM_TEMPLATE_LINK> ADM_TEMPLATE_LINK { get; set; }
        public virtual ICollection<ADM_TEMPLATE_REMINDER> ADM_TEMPLATE_REMINDER { get; set; }
        public virtual ICollection<AUX_ACTIVITY_TYPE_CAP_CLASS> AUX_ACTIVITY_TYPE_CAP_CLASS { get; set; }
        public virtual ICollection<AUX_KIT_TEMPLATE> AUX_KIT_TEMPLATE { get; set; }
        public virtual ICollection<PRC_ACTIVITY> PRC_ACTIVITY { get; set; }
        public virtual ICollection<PRC_RECURRENCE_ACTIVITY> PRC_RECURRENCE_ACTIVITY { get; set; }
        public virtual ICollection<AUX_CAP_CODE> AUX_CAP_CODE { get; set; }
    }
}
