//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_LINK
    {
        public ADM_LINK()
        {
            this.ADM_LINK_LOCALIZED = new HashSet<ADM_LINK_LOCALIZED>();
            this.ADM_TEMPLATE_LINK = new HashSet<ADM_TEMPLATE_LINK>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SYS_CODE { get; set; }
        public Nullable<int> LOB_ID { get; set; }
        public string URL { get; set; }
        public short DEPTH { get; set; }
        public short INCLUDE_IMAGE { get; set; }
        public System.DateTime EFFECTIVE_DATETIME { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual SYS_LOB SYS_LOB { get; set; }
        public virtual ICollection<ADM_LINK_LOCALIZED> ADM_LINK_LOCALIZED { get; set; }
        public virtual ICollection<ADM_TEMPLATE_LINK> ADM_TEMPLATE_LINK { get; set; }
    }
}
