//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_CUSTOMER_CATEGORY_LOCALIZED
    {
        public short ID { get; set; }
        public string CULTURE { get; set; }
        public string NAME { get; set; }
        public short SEQUENCE { get; set; }
        public short CUSTOMER_TYPE { get; set; }
        public short ALLOW_INSERT { get; set; }
        public short ALLOW_UPDATE { get; set; }
        public string NON_EDITABLE_FIELDS { get; set; }
        public string ALLOW_SUCCESSOR { get; set; }
        public string LABEL { get; set; }
        public string COLUMN_NAME { get; set; }
        public short DATA_TYPE { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_CUSTOMER_CATEGORY ADM_CUSTOMER_CATEGORY { get; set; }
    }
}
