//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_USER
    {
        public ADM_USER()
        {
            this.ADM_TERRITORY_ACCESS = new HashSet<ADM_TERRITORY_ACCESS>();
            this.AUX_CUSTOM_ADDRESS = new HashSet<AUX_CUSTOM_ADDRESS>();
            this.AUX_SALES_ORDER = new HashSet<AUX_SALES_ORDER>();
            this.AUX_TRUNK_ORDER = new HashSet<AUX_TRUNK_ORDER>();
            this.MED_CASE = new HashSet<MED_CASE>();
            this.MED_CASE1 = new HashSet<MED_CASE>();
            this.MED_SUPPORT_CONTACT = new HashSet<MED_SUPPORT_CONTACT>();
            this.MED_POST_BILL = new HashSet<MED_POST_BILL>();
            this.MED_POST_BILL1 = new HashSet<MED_POST_BILL>();
            this.MED_SALES_ORDER = new HashSet<MED_SALES_ORDER>();
            this.MED_SALES_ORDER1 = new HashSet<MED_SALES_ORDER>();
            this.MED_TRUNK_ORDER = new HashSet<MED_TRUNK_ORDER>();
            this.MED_TRUNK_ORDER1 = new HashSet<MED_TRUNK_ORDER>();
            this.ADM_USER_ABSENCE = new HashSet<ADM_USER_ABSENCE>();
            this.ADM_USER_ABSENCE1 = new HashSet<ADM_USER_ABSENCE>();
            this.ADM_USER_DIST = new HashSet<ADM_USER_DIST>();
            this.AUX_CASE_NOTE = new HashSet<AUX_CASE_NOTE>();
            this.AUX_CASE_PRODUCT_TRACK = new HashSet<AUX_CASE_PRODUCT_TRACK>();
            this.AUX_PRODUCT_ORDER = new HashSet<AUX_PRODUCT_ORDER>();
            this.AUX_REGION = new HashSet<AUX_REGION>();
            this.EXC_AGING_QUEUE = new HashSet<EXC_AGING_QUEUE>();
            this.EXC_ERROR_LOG = new HashSet<EXC_ERROR_LOG>();
            this.EXC_LOGIN_LOG = new HashSet<EXC_LOGIN_LOG>();
            this.EXC_MESSAGE_QUEUE = new HashSet<EXC_MESSAGE_QUEUE>();
            this.EXC_USER_CONTEXT = new HashSet<EXC_USER_CONTEXT>();
            this.EXC_GDID_MAP = new HashSet<EXC_GDID_MAP>();
            this.MED_KIT = new HashSet<MED_KIT>();
            this.MED_POST_BILL2 = new HashSet<MED_POST_BILL>();
            this.PRC_ACTION = new HashSet<PRC_ACTION>();
            this.PRC_ACTIVITY = new HashSet<PRC_ACTIVITY>();
            this.PRC_CONTACT_MAP = new HashSet<PRC_CONTACT_MAP>();
            this.PRC_CUSTOMER = new HashSet<PRC_CUSTOMER>();
            this.PRC_DIARY = new HashSet<PRC_DIARY>();
            this.PRC_NOTE = new HashSet<PRC_NOTE>();
            this.PRC_RECURRENCE_ACTIVITY = new HashSet<PRC_RECURRENCE_ACTIVITY>();
            this.EXC_USER_COMPONENT_TRACKING = new HashSet<EXC_USER_COMPONENT_TRACKING>();
        }
    
        public int ID { get; set; }
        public string LOGIN_NAME { get; set; }
        public string LOB_NATIVE_IDENTIFIER { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public int ORG_LEVEL_ID { get; set; }
        public int AUTHORITY_TYPE_ID { get; set; }
        public int TIMEZONE_LIST_ID { get; set; }
        public short MIS_MESSAGE_ENABLED { get; set; }
        public string NOTIFICATION_ADDRESS { get; set; }
        public string STREET_1 { get; set; }
        public string STREET_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTAL_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE { get; set; }
        public string MOBILE_PHONE { get; set; }
        public short VISIBLE_STATUS { get; set; }
        public System.DateTime EFFECTIVE_DATETIME { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_AUTHORITY_TYPE ADM_AUTHORITY_TYPE { get; set; }
        public virtual ADM_LIST ADM_LIST { get; set; }
        public virtual ADM_ORG_LEVEL ADM_ORG_LEVEL { get; set; }
        public virtual ICollection<ADM_TERRITORY_ACCESS> ADM_TERRITORY_ACCESS { get; set; }
        public virtual AUX_USER AUX_USER { get; set; }
        public virtual ICollection<AUX_CUSTOM_ADDRESS> AUX_CUSTOM_ADDRESS { get; set; }
        public virtual ICollection<AUX_SALES_ORDER> AUX_SALES_ORDER { get; set; }
        public virtual ICollection<AUX_TRUNK_ORDER> AUX_TRUNK_ORDER { get; set; }
        public virtual ICollection<MED_CASE> MED_CASE { get; set; }
        public virtual ICollection<MED_CASE> MED_CASE1 { get; set; }
        public virtual ICollection<MED_SUPPORT_CONTACT> MED_SUPPORT_CONTACT { get; set; }
        public virtual ICollection<MED_POST_BILL> MED_POST_BILL { get; set; }
        public virtual ICollection<MED_POST_BILL> MED_POST_BILL1 { get; set; }
        public virtual ICollection<MED_SALES_ORDER> MED_SALES_ORDER { get; set; }
        public virtual ICollection<MED_SALES_ORDER> MED_SALES_ORDER1 { get; set; }
        public virtual ICollection<MED_TRUNK_ORDER> MED_TRUNK_ORDER { get; set; }
        public virtual ICollection<MED_TRUNK_ORDER> MED_TRUNK_ORDER1 { get; set; }
        public virtual ICollection<ADM_USER_ABSENCE> ADM_USER_ABSENCE { get; set; }
        public virtual ICollection<ADM_USER_ABSENCE> ADM_USER_ABSENCE1 { get; set; }
        public virtual ICollection<ADM_USER_DIST> ADM_USER_DIST { get; set; }
        public virtual ICollection<AUX_CASE_NOTE> AUX_CASE_NOTE { get; set; }
        public virtual ICollection<AUX_CASE_PRODUCT_TRACK> AUX_CASE_PRODUCT_TRACK { get; set; }
        public virtual ICollection<AUX_PRODUCT_ORDER> AUX_PRODUCT_ORDER { get; set; }
        public virtual ICollection<AUX_REGION> AUX_REGION { get; set; }
        public virtual ICollection<EXC_AGING_QUEUE> EXC_AGING_QUEUE { get; set; }
        public virtual EXC_CONNECTED_USER EXC_CONNECTED_USER { get; set; }
        public virtual ICollection<EXC_ERROR_LOG> EXC_ERROR_LOG { get; set; }
        public virtual EXC_LAST_SYNC EXC_LAST_SYNC { get; set; }
        public virtual ICollection<EXC_LOGIN_LOG> EXC_LOGIN_LOG { get; set; }
        public virtual ICollection<EXC_MESSAGE_QUEUE> EXC_MESSAGE_QUEUE { get; set; }
        public virtual ICollection<EXC_USER_CONTEXT> EXC_USER_CONTEXT { get; set; }
        public virtual EXC_WORKLOAD EXC_WORKLOAD { get; set; }
        public virtual ICollection<EXC_GDID_MAP> EXC_GDID_MAP { get; set; }
        public virtual ICollection<MED_KIT> MED_KIT { get; set; }
        public virtual ICollection<MED_POST_BILL> MED_POST_BILL2 { get; set; }
        public virtual ICollection<PRC_ACTION> PRC_ACTION { get; set; }
        public virtual ICollection<PRC_ACTIVITY> PRC_ACTIVITY { get; set; }
        public virtual ICollection<PRC_CONTACT_MAP> PRC_CONTACT_MAP { get; set; }
        public virtual ICollection<PRC_CUSTOMER> PRC_CUSTOMER { get; set; }
        public virtual ICollection<PRC_DIARY> PRC_DIARY { get; set; }
        public virtual ICollection<PRC_NOTE> PRC_NOTE { get; set; }
        public virtual ICollection<PRC_RECURRENCE_ACTIVITY> PRC_RECURRENCE_ACTIVITY { get; set; }
        public virtual ICollection<EXC_USER_COMPONENT_TRACKING> EXC_USER_COMPONENT_TRACKING { get; set; }
    }
}
