//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_CONTACT_TYPE
    {
        public ADM_CONTACT_TYPE()
        {
            this.ADM_CONTACT_TYPE_LOCALIZED = new HashSet<ADM_CONTACT_TYPE_LOCALIZED>();
            this.PRC_CONTACT = new HashSet<PRC_CONTACT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SYS_CODE { get; set; }
        public short USER_CREATABLE { get; set; }
        public System.DateTime EFFECTIVE_DATETIME { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<ADM_CONTACT_TYPE_LOCALIZED> ADM_CONTACT_TYPE_LOCALIZED { get; set; }
        public virtual ICollection<PRC_CONTACT> PRC_CONTACT { get; set; }
    }
}
