//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_ACTION_TYPE
    {
        public ADM_ACTION_TYPE()
        {
            this.ADM_ACTION_TYPE_LOCALIZED = new HashSet<ADM_ACTION_TYPE_LOCALIZED>();
            this.ADM_TEMPLATE_ACTION = new HashSet<ADM_TEMPLATE_ACTION>();
            this.PRC_ACTION = new HashSet<PRC_ACTION>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string SYS_CODE { get; set; }
        public Nullable<int> LOB_ID { get; set; }
        public double DURATION { get; set; }
        public short PRIORITY { get; set; }
        public short DISTRIBUTION_PARENT_OVERRIDE { get; set; }
        public int WEIGHT { get; set; }
        public Nullable<double> AGING_DURATION { get; set; }
        public System.DateTime EFFECTIVE_DATETIME { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual SYS_LOB SYS_LOB { get; set; }
        public virtual ICollection<ADM_ACTION_TYPE_LOCALIZED> ADM_ACTION_TYPE_LOCALIZED { get; set; }
        public virtual ICollection<ADM_TEMPLATE_ACTION> ADM_TEMPLATE_ACTION { get; set; }
        public virtual ICollection<PRC_ACTION> PRC_ACTION { get; set; }
    }
}
