//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_LIST
    {
        public ADM_LIST()
        {
            this.MED_SALES_CALL = new HashSet<MED_SALES_CALL>();
            this.AUX_USER = new HashSet<AUX_USER>();
            this.ADM_LIST_LOCALIZED = new HashSet<ADM_LIST_LOCALIZED>();
            this.ADM_USER = new HashSet<ADM_USER>();
            this.PRC_DIARY = new HashSet<PRC_DIARY>();
        }
    
        public int ID { get; set; }
        public int LIST_TYPE_ID { get; set; }
        public string NAME { get; set; }
        public string VALUE { get; set; }
        public short ORDER_NUMBER { get; set; }
        public System.DateTime EFFECTIVE_DATETIME { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<MED_SALES_CALL> MED_SALES_CALL { get; set; }
        public virtual ICollection<AUX_USER> AUX_USER { get; set; }
        public virtual SYS_LIST_TYPE SYS_LIST_TYPE { get; set; }
        public virtual ICollection<ADM_LIST_LOCALIZED> ADM_LIST_LOCALIZED { get; set; }
        public virtual ICollection<ADM_USER> ADM_USER { get; set; }
        public virtual ICollection<PRC_DIARY> PRC_DIARY { get; set; }
    }
}
