//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_AUX_LIST
    {
        public ADM_AUX_LIST()
        {
            this.ADM_AUX_LIST1 = new HashSet<ADM_AUX_LIST>();
            this.MED_CASE = new HashSet<MED_CASE>();
            this.MED_POST_BILL = new HashSet<MED_POST_BILL>();
            this.MED_TRUNK_ORDER = new HashSet<MED_TRUNK_ORDER>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public int LIST_TYPE_ID { get; set; }
        public string NAME { get; set; }
        public string VALUE { get; set; }
        public string DATA1 { get; set; }
        public string DATA2 { get; set; }
        public string DATA3 { get; set; }
        public short SEQUENCE_NUM { get; set; }
        public string DESCRIPTION { get; set; }
        public short HIDDEN_FLAG { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<ADM_AUX_LIST> ADM_AUX_LIST1 { get; set; }
        public virtual ADM_AUX_LIST ADM_AUX_LIST2 { get; set; }
        public virtual ICollection<MED_CASE> MED_CASE { get; set; }
        public virtual ICollection<MED_POST_BILL> MED_POST_BILL { get; set; }
        public virtual ICollection<MED_TRUNK_ORDER> MED_TRUNK_ORDER { get; set; }
        public virtual SYS_AUX_LIST_TYPE SYS_AUX_LIST_TYPE { get; set; }
    }
}
