//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_CONTENT_TYPE
    {
        public ADM_CONTENT_TYPE()
        {
            this.ADM_CONTENT = new HashSet<ADM_CONTENT>();
            this.ADM_PROCESS_SERVICE = new HashSet<ADM_PROCESS_SERVICE>();
            this.ADM_CONTENT_TYPE_LOCALIZED = new HashSet<ADM_CONTENT_TYPE_LOCALIZED>();
            this.ADM_TEMPLATE_ATTACHMENT = new HashSet<ADM_TEMPLATE_ATTACHMENT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SYS_CODE { get; set; }
        public Nullable<int> LOB_ID { get; set; }
        public Nullable<short> FORMAT { get; set; }
        public string FILE_PROMPT { get; set; }
        public string FILE_EXTENSIONS { get; set; }
        public short RETURN_TYPE { get; set; }
        public short READ_ONLY { get; set; }
        public short ALLOWED_ORGINATOR { get; set; }
        public short REFERENCE { get; set; }
        public short RETENTION_DURATION { get; set; }
        public int EMAIL_MODE { get; set; }
        public System.DateTime EFFECTIVE_DATETIME { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<ADM_CONTENT> ADM_CONTENT { get; set; }
        public virtual ICollection<ADM_PROCESS_SERVICE> ADM_PROCESS_SERVICE { get; set; }
        public virtual SYS_LOB SYS_LOB { get; set; }
        public virtual ICollection<ADM_CONTENT_TYPE_LOCALIZED> ADM_CONTENT_TYPE_LOCALIZED { get; set; }
        public virtual ICollection<ADM_TEMPLATE_ATTACHMENT> ADM_TEMPLATE_ATTACHMENT { get; set; }
    }
}
