//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADP_LOB_DATA_MAP
    {
        public string ENDPOINT_SYSTEM { get; set; }
        public string VERSION { get; set; }
        public int MODULE { get; set; }
        public int FUNCTION_ID { get; set; }
        public int FUNCTION_INDEX { get; set; }
        public int SEQ_NUM { get; set; }
        public string SOURCE_FIELD { get; set; }
        public string DESTINATION_FIELD { get; set; }
        public short DATA_TYPE { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    }
}
