//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_PART_MASTER
    {
        public int ID { get; set; }
        public string PART_NUMBER { get; set; }
        public string PART_NAME { get; set; }
        public string PART_BARCODE { get; set; }
        public string PART_DESCRIPTION { get; set; }
        public Nullable<decimal> PART_LIST_PRICE { get; set; }
        public string PART_UNIT_MEASURE { get; set; }
        public Nullable<int> PART_PACKAGE_QTY { get; set; }
        public short PART_LOT_REQUIRED_FLAG { get; set; }
        public short PART_LIVE_FLAG { get; set; }
        public short PART_KIT_ONLY_FLAG { get; set; }
        public string PART_LOB_CATEGORY { get; set; }
        public short PART_MBM_LOCK_FLAG { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_NAME { get; set; }
        public string LINE_DESCRIPTION { get; set; }
        public Nullable<short> LINE_SEQUENCE_NUM { get; set; }
        public short LINE_SCANNABLE_FLAG { get; set; }
        public short LINE_LIVE_FLAG { get; set; }
        public short LINE_HIDE_FLAG { get; set; }
        public Nullable<short> LINE_DELETE_FLAG { get; set; }
        public string BRAND_CODE { get; set; }
        public string BRAND_NAME { get; set; }
        public string BRAND_DESCRIPTION { get; set; }
        public Nullable<short> BRAND_SEQUENCE_NUM { get; set; }
        public short BRAND_HIDE_FLAG { get; set; }
        public Nullable<short> BRAND_DELETE_FLAG { get; set; }
        public string COMPONENT_CODE { get; set; }
        public string COMPONENT_NAME { get; set; }
        public string COMPONENT_DESCRIPTION { get; set; }
        public Nullable<short> COMPONENT_SEQUENCE_NUM { get; set; }
        public short COMPONENT_HIDE_FLAG { get; set; }
        public Nullable<short> COMPONENT_DELETE_FLAG { get; set; }
        public short KIT_FLAG { get; set; }
        public string OPERATION_TYPE { get; set; }
        public short CHANGE_TYPE { get; set; }
        public short IS_IN_FEED { get; set; }
        public short REJECTED_FLAG { get; set; }
        public short DELETE_FLAG { get; set; }
        public short ERROR_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    }
}
