//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_CLPARTLIST_MASTER
    {
        public int ID { get; set; }
        public string KIT_INSTANCE_NAME { get; set; }
        public string KIT_BLUEPRINT_NUMBER { get; set; }
        public string ORDER_NUMBER { get; set; }
        public string LOT_CODES { get; set; }
        public string EXPIRATION_DATETIMES { get; set; }
        public int QTY { get; set; }
        public string OPERATION_TYPE { get; set; }
        public short CHANGE_TYPE { get; set; }
        public short IS_IN_FEED { get; set; }
        public short DELETE_FLAG { get; set; }
        public short ERROR_FLAG { get; set; }
        public short REJECTED_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
        public string CASE_ID { get; set; }
        public string KIT_SERIAL_NUMBER { get; set; }
        public string ASSET_TAG { get; set; }
        public string TRACKING_NUMBER { get; set; }
        public string TERRITORY_NUMBER { get; set; }
        public string PART_NUMBER { get; set; }
    }
}
