//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_SURGEON_MASTER
    {
        public int ID { get; set; }
        public string LOB_NATIVE_IDENTIFIER { get; set; }
        public string SURGEON_IDENTIFIER { get; set; }
        public string HOSPITAL_IDENTIFIER { get; set; }
        public string TITLE { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME_LCASE { get; set; }
        public string MIDDLE_NAME_LCASE { get; set; }
        public string LAST_NAME_LCASE { get; set; }
        public string SUFFIX { get; set; }
        public string JOB_TITLE { get; set; }
        public string DEPARTMENT { get; set; }
        public string COMPANY_NAME { get; set; }
        public string BUSINESS_TELEPHONE_NUMBER { get; set; }
        public string BUSINESS2_TELEPHONE_NUMBER { get; set; }
        public string HOME_TELEPHONE_NUMBER { get; set; }
        public string HOME2_TELEPHONE_NUMBER { get; set; }
        public string MOBILE_TELEPHONE_NUMBER { get; set; }
        public string PAGER_NUMBER { get; set; }
        public string CAR_TELEPHONE_NUMBER { get; set; }
        public string BUSINESS_FAX_NUMBER { get; set; }
        public string HOME_FAX_NUMBER { get; set; }
        public string ASSISTANT_TELEPHONE_NUMBER { get; set; }
        public string ASSISTANT_NAME { get; set; }
        public string RADIO_TELEPHONE_NUMBER { get; set; }
        public string EMAIL1_ADDRESS { get; set; }
        public string EMAIL2_ADDRESS { get; set; }
        public string EMAIL3_ADDRESS { get; set; }
        public string WEB_PAGE { get; set; }
        public string BUSINESS_ADDRESS_STREET1 { get; set; }
        public string BUSINESS_ADDRESS_STREET2 { get; set; }
        public string BUSINESS_ADDRESS_CITY { get; set; }
        public string BUSINESS_ADDRESS_STATE { get; set; }
        public string BUSINESS_ADDRESS_POSTAL_CODE { get; set; }
        public string BUSINESS_ADDRESS_COUNTRY { get; set; }
        public string OFFICE_LOCATION { get; set; }
        public string HOME_ADDRESS_STREET1 { get; set; }
        public string HOME_ADDRESS_STREET2 { get; set; }
        public string HOME_ADDRESS_CITY { get; set; }
        public string HOME_ADDRESS_STATE { get; set; }
        public string HOME_ADDRESS_POSTAL_CODE { get; set; }
        public string HOME_ADDRESS_COUNTRY { get; set; }
        public string OTHER_ADDRESS_STREET1 { get; set; }
        public string OTHER_ADDRESS_STREET2 { get; set; }
        public string OTHER_ADDRESS_CITY { get; set; }
        public string OTHER_ADDRESS_STATE { get; set; }
        public string OTHER_ADDRESS_POSTAL_CODE { get; set; }
        public string OTHER_ADDRESS_COUNTRY { get; set; }
        public string GENDER { get; set; }
        public string SPECIALTY { get; set; }
        public string DEA_NUMBER { get; set; }
        public string ME_NUMBER { get; set; }
        public string IMS_NUMBER { get; set; }
        public string OFFICE_HOURS { get; set; }
        public string OR_HOURS { get; set; }
        public short CHANGE_TYPE { get; set; }
        public short IS_IN_FEED { get; set; }
        public short DELETE_FLAG { get; set; }
        public short ERROR_FLAG { get; set; }
        public short REJECTED_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    }
}
