//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_PRODUCT
    {
        public AUX_PRODUCT()
        {
            this.AUX_BIN_PRODUCT = new HashSet<AUX_BIN_PRODUCT>();
            this.AUX_CASE_PRODUCT = new HashSet<AUX_CASE_PRODUCT>();
            this.AUX_CASE_PRODUCT_AUGMENT = new HashSet<AUX_CASE_PRODUCT_AUGMENT>();
            this.AUX_INVENTORY_TRACK = new HashSet<AUX_INVENTORY_TRACK>();
            this.AUX_KIT_CONTENT = new HashSet<AUX_KIT_CONTENT>();
            this.AUX_KIT_INSTANCE_PRODUCT = new HashSet<AUX_KIT_INSTANCE_PRODUCT>();
            this.AUX_PRODUCT_IMAGE = new HashSet<AUX_PRODUCT_IMAGE>();
            this.AUX_SALES_ORDER_PRODUCT = new HashSet<AUX_SALES_ORDER_PRODUCT>();
            this.AUX_SKU_GROUP_CONTENT = new HashSet<AUX_SKU_GROUP_CONTENT>();
            this.AUX_TRUNK_ORDER_PRODUCT = new HashSet<AUX_TRUNK_ORDER_PRODUCT>();
            this.AUX_PRODUCT_ORDER_PART = new HashSet<AUX_PRODUCT_ORDER_PART>();
            this.AUX_VALIDATION_DETAILS = new HashSet<AUX_VALIDATION_DETAILS>();
        }
    
        public int ID { get; set; }
        public Nullable<int> COMPONENT_ID { get; set; }
        public string PART_NUMBER { get; set; }
        public string BARCODE { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal LIST_PRICE { get; set; }
        public Nullable<decimal> AUX_PRICE { get; set; }
        public Nullable<decimal> LOAD_PRICE { get; set; }
        public string UNIT_MEASURE { get; set; }
        public Nullable<short> PACKAGE_QTY { get; set; }
        public short LOT_REQUIRED_FLAG { get; set; }
        public short LIVE_FLAG { get; set; }
        public short KIT_ONLY_FLAG { get; set; }
        public string LOB_CATEGORY { get; set; }
        public short MBM_LOCK_FLAG { get; set; }
        public short DELETE_FLAG { get; set; }
        public Nullable<System.DateTime> DELETE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<AUX_BIN_PRODUCT> AUX_BIN_PRODUCT { get; set; }
        public virtual ICollection<AUX_CASE_PRODUCT> AUX_CASE_PRODUCT { get; set; }
        public virtual ICollection<AUX_CASE_PRODUCT_AUGMENT> AUX_CASE_PRODUCT_AUGMENT { get; set; }
        public virtual ICollection<AUX_INVENTORY_TRACK> AUX_INVENTORY_TRACK { get; set; }
        public virtual ICollection<AUX_KIT_CONTENT> AUX_KIT_CONTENT { get; set; }
        public virtual ICollection<AUX_KIT_INSTANCE_PRODUCT> AUX_KIT_INSTANCE_PRODUCT { get; set; }
        public virtual AUX_PART_COMPONENT AUX_PART_COMPONENT { get; set; }
        public virtual ICollection<AUX_PRODUCT_IMAGE> AUX_PRODUCT_IMAGE { get; set; }
        public virtual ICollection<AUX_SALES_ORDER_PRODUCT> AUX_SALES_ORDER_PRODUCT { get; set; }
        public virtual ICollection<AUX_SKU_GROUP_CONTENT> AUX_SKU_GROUP_CONTENT { get; set; }
        public virtual ICollection<AUX_TRUNK_ORDER_PRODUCT> AUX_TRUNK_ORDER_PRODUCT { get; set; }
        public virtual ICollection<AUX_PRODUCT_ORDER_PART> AUX_PRODUCT_ORDER_PART { get; set; }
        public virtual ICollection<AUX_VALIDATION_DETAILS> AUX_VALIDATION_DETAILS { get; set; }
    }
}
