//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_ACCOUNT_PRICE
    {
        public int ID { get; set; }
        public int FACILITY_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public decimal PRICE { get; set; }
        public System.DateTime VALID_FROM_DATETIME { get; set; }
        public System.DateTime VALID_TO_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual AUX_FACILITY AUX_FACILITY { get; set; }
    }
}
