//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_FACILITY
    {
        public AUX_FACILITY()
        {
            this.AUX_ACCOUNT_PRICE = new HashSet<AUX_ACCOUNT_PRICE>();
            this.AUX_CAP_CODE = new HashSet<AUX_CAP_CODE>();
            this.AUX_CASE = new HashSet<AUX_CASE>();
            this.AUX_SALES_ORDER = new HashSet<AUX_SALES_ORDER>();
            this.AUX_SURGEON_FACILITY = new HashSet<AUX_SURGEON_FACILITY>();
            this.MED_FACILITY_DEPARTMENT = new HashSet<MED_FACILITY_DEPARTMENT>();
        }
    
        public int CUSTOMER_ID { get; set; }
        public int CUSTOMER_CONTACT_ID { get; set; }
        public string FACILITY_TYPE { get; set; }
        public int REGION_ID { get; set; }
        public string ACCOUNT_NUMBER { get; set; }
        public string BILL_TO_NUMBER { get; set; }
        public string PURCHASE_GROUP { get; set; }
        public short DISCOUNT_RATE { get; set; }
        public string HEALTH_INDUSTRY_NUMBER { get; set; }
        public int PRIMARY_WAREHOUSE_ID { get; set; }
        public Nullable<int> FACILITY_WAREHOUSE_ID { get; set; }
        public string DATA1 { get; set; }
        public string DATA2 { get; set; }
        public string DATA3 { get; set; }
        public short TEST_FLAG { get; set; }
        public string SOURCE { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<AUX_ACCOUNT_PRICE> AUX_ACCOUNT_PRICE { get; set; }
        public virtual ICollection<AUX_CAP_CODE> AUX_CAP_CODE { get; set; }
        public virtual ICollection<AUX_CASE> AUX_CASE { get; set; }
        public virtual ICollection<AUX_SALES_ORDER> AUX_SALES_ORDER { get; set; }
        public virtual ICollection<AUX_SURGEON_FACILITY> AUX_SURGEON_FACILITY { get; set; }
        public virtual ICollection<MED_FACILITY_DEPARTMENT> MED_FACILITY_DEPARTMENT { get; set; }
        public virtual AUX_REGION AUX_REGION { get; set; }
        public virtual AUX_WAREHOUSE AUX_WAREHOUSE { get; set; }
        public virtual AUX_WAREHOUSE AUX_WAREHOUSE1 { get; set; }
        public virtual PRC_CONTACT PRC_CONTACT { get; set; }
        public virtual PRC_CUSTOMER PRC_CUSTOMER { get; set; }
    }
}
