//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_REGION
    {
        public AUX_REGION()
        {
            this.AUX_FACILITY = new HashSet<AUX_FACILITY>();
            this.AUX_SURGEON = new HashSet<AUX_SURGEON>();
            this.AUX_USER = new HashSet<AUX_USER>();
        }
    
        public int ID { get; set; }
        public int BILLING_COORDINATOR_ID { get; set; }
        public int TERRITORY_ID { get; set; }
        public string IDENTIFIER { get; set; }
        public string NAME { get; set; }
        public short HIDE_FLAG { get; set; }
        public Nullable<System.DateTime> HIDE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_USER ADM_USER { get; set; }
        public virtual ICollection<AUX_FACILITY> AUX_FACILITY { get; set; }
        public virtual ICollection<AUX_SURGEON> AUX_SURGEON { get; set; }
        public virtual ICollection<AUX_USER> AUX_USER { get; set; }
        public virtual AUX_TERRITORY AUX_TERRITORY { get; set; }
    }
}
