//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_KIT_INSTANCE_TRACK
    {
        public int ID { get; set; }
        public int KIT_INSTANCE_ID { get; set; }
        public Nullable<int> CASE_ID { get; set; }
        public string ATTRIBUTE_TYPE { get; set; }
        public string VALUE { get; set; }
        public string ADDITIONAL_VALUES_XML { get; set; }
        public System.DateTime TRANSACTION_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
    
        public virtual AUX_CASE AUX_CASE { get; set; }
        public virtual AUX_KIT_INSTANCE AUX_KIT_INSTANCE { get; set; }
    }
}
