//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_VALIDATION_LOG
    {
        public AUX_VALIDATION_LOG()
        {
            this.AUX_VALIDATION_DETAILS = new HashSet<AUX_VALIDATION_DETAILS>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public string CONTAINER_TYPE { get; set; }
        public Nullable<int> CONTAINER_ID { get; set; }
        public Nullable<int> EXPECTED_COUNT { get; set; }
        public Nullable<int> FOUND_COUNT { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<AUX_VALIDATION_DETAILS> AUX_VALIDATION_DETAILS { get; set; }
    }
}
