//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_CLBLUEPRINT_MASTER
    {
        public int ID { get; set; }
        public string COMPONENT_CODE { get; set; }
        public string KIT_NUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> DELIVERY_DAYS { get; set; }
        public Nullable<int> RETURN_DAYS { get; set; }
        public string KIT_OPERATION_TYPE { get; set; }
        public int QTY { get; set; }
        public string OPERATION_TYPE { get; set; }
        public short CHANGE_TYPE { get; set; }
        public short IS_IN_FEED { get; set; }
        public short DELETE_FLAG { get; set; }
        public short ERROR_FLAG { get; set; }
        public short REJECTED_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
        public string LINE_CODE { get; set; }
        public string BRAND_CODE { get; set; }
        public string NAME { get; set; }
        public string KIT_TYPE_LV { get; set; }
        public string TERRITORY_NUMBER { get; set; }
        public string PART_NUMBER { get; set; }
        public short ITEM_NUMBER { get; set; }
    }
}
