//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_CAP_CODE_MASTER
    {
        public int ID { get; set; }
        public string CAP_CODE { get; set; }
        public string CAP_CODE_DESCRIPTION { get; set; }
        public string CLASS { get; set; }
        public string BILL_TO_NUMBER { get; set; }
        public decimal PRICE { get; set; }
        public string PRIMARY_ADDITIONAL { get; set; }
        public string OPERATION_TYPE { get; set; }
        public short CHANGE_TYPE { get; set; }
        public short IS_IN_FEED { get; set; }
        public short DELETE_FLAG { get; set; }
        public short ERROR_FLAG { get; set; }
        public short REJECTED_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    }
}
