//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_PRODUCT_LINE
    {
        public AUX_PRODUCT_LINE()
        {
            this.AUX_CASE_TYPE = new HashSet<AUX_CASE_TYPE>();
            this.AUX_KIT = new HashSet<AUX_KIT>();
            this.AUX_PRODUCT_BRAND = new HashSet<AUX_PRODUCT_BRAND>();
            this.AUX_SKU_GROUP = new HashSet<AUX_SKU_GROUP>();
        }
    
        public int ID { get; set; }
        public int TERRITORY_ID { get; set; }
        public string LOB_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public short SEQUENCE_NUM { get; set; }
        public short SCANNABLE_FLAG { get; set; }
        public short LIVE_FLAG { get; set; }
        public short HIDE_FLAG { get; set; }
        public short DELETE_FLAG { get; set; }
        public Nullable<System.DateTime> DELETE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<AUX_CASE_TYPE> AUX_CASE_TYPE { get; set; }
        public virtual ICollection<AUX_KIT> AUX_KIT { get; set; }
        public virtual ICollection<AUX_PRODUCT_BRAND> AUX_PRODUCT_BRAND { get; set; }
        public virtual ICollection<AUX_SKU_GROUP> AUX_SKU_GROUP { get; set; }
        public virtual AUX_TERRITORY AUX_TERRITORY { get; set; }
    }
}
