//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_CASE_PRODUCT
    {
        public AUX_CASE_PRODUCT()
        {
            this.AUX_CASE_PRODUCT_AUGMENT = new HashSet<AUX_CASE_PRODUCT_AUGMENT>();
            this.AUX_CASE_PRODUCT_CONFLICT = new HashSet<AUX_CASE_PRODUCT_CONFLICT>();
            this.AUX_CASE_PRODUCT_TRACK = new HashSet<AUX_CASE_PRODUCT_TRACK>();
        }
    
        public int ID { get; set; }
        public int TERRITORY_ID { get; set; }
        public int CASE_ID { get; set; }
        public Nullable<int> NEXT_CASE_ID { get; set; }
        public Nullable<int> KIT_ID { get; set; }
        public Nullable<int> KIT_INSTANCE_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public string STATUS_LV { get; set; }
        public int QTY { get; set; }
        public string SHIP_METHOD_LV { get; set; }
        public string SHIP_TRACKING_NUM { get; set; }
        public string SHIP_ADDRESS_TYPE { get; set; }
        public Nullable<int> SHIP_TO_ADDRESS_ID { get; set; }
        public string SHIP_ATTENTION { get; set; }
        public string SHIP_NOTE { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public Nullable<System.DateTime> SHIP_DATE { get; set; }
        public Nullable<System.DateTime> DELIVERED_DATE { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public string SOURCE_LOCATION_LV { get; set; }
        public string ORDER_NUMBER { get; set; }
        public short SUPPORT_FLAG { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual AUX_CASE AUX_CASE { get; set; }
        public virtual AUX_KIT AUX_KIT { get; set; }
        public virtual AUX_KIT_INSTANCE AUX_KIT_INSTANCE { get; set; }
        public virtual AUX_PRODUCT AUX_PRODUCT { get; set; }
        public virtual ICollection<AUX_CASE_PRODUCT_AUGMENT> AUX_CASE_PRODUCT_AUGMENT { get; set; }
        public virtual ICollection<AUX_CASE_PRODUCT_CONFLICT> AUX_CASE_PRODUCT_CONFLICT { get; set; }
        public virtual AUX_TERRITORY AUX_TERRITORY { get; set; }
        public virtual ICollection<AUX_CASE_PRODUCT_TRACK> AUX_CASE_PRODUCT_TRACK { get; set; }
    }
}
