//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_PART_COMPONENT
    {
        public AUX_PART_COMPONENT()
        {
            this.AUX_PRODUCT = new HashSet<AUX_PRODUCT>();
        }
    
        public int ID { get; set; }
        public int BRAND_ID { get; set; }
        public string LOB_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public short SEQUENCE_NUM { get; set; }
        public short HIDE_FLAG { get; set; }
        public short DELETE_FLAG { get; set; }
        public Nullable<System.DateTime> DELETE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual AUX_PART_BRAND AUX_PART_BRAND { get; set; }
        public virtual ICollection<AUX_PRODUCT> AUX_PRODUCT { get; set; }
    }
}
