//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_KIT_IMAGE
    {
        public int KIT_ID { get; set; }
        public short SEQUENCE_NUMBER { get; set; }
        public string IMAGE_URL { get; set; }
        public byte[] SMALL_FORMAT_IMAGE { get; set; }
        public byte[] LARGE_FORMAT_IMAGE { get; set; }
        public int SYNC_STATUS { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual AUX_KIT AUX_KIT { get; set; }
    }
}
