//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_WAREHOUSE
    {
        public AUX_WAREHOUSE()
        {
            this.AUX_BIN = new HashSet<AUX_BIN>();
            this.AUX_FACILITY = new HashSet<AUX_FACILITY>();
            this.AUX_FACILITY1 = new HashSet<AUX_FACILITY>();
            this.AUX_KIT_INSTANCE = new HashSet<AUX_KIT_INSTANCE>();
            this.AUX_KIT_INSTANCE1 = new HashSet<AUX_KIT_INSTANCE>();
            this.AUX_PRODUCT_ORDER = new HashSet<AUX_PRODUCT_ORDER>();
            this.AUX_PRODUCT_ORDER1 = new HashSet<AUX_PRODUCT_ORDER>();
            this.AUX_USER = new HashSet<AUX_USER>();
            this.AUX_USER1 = new HashSet<AUX_USER>();
        }
    
        public int ID { get; set; }
        public int TERRITORY_ID { get; set; }
        public string NAME { get; set; }
        public string TYPE_LV { get; set; }
        public string IDENTIFIER { get; set; }
        public string STREET1 { get; set; }
        public string STREET2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTAL_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public short DELETE_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<AUX_BIN> AUX_BIN { get; set; }
        public virtual ICollection<AUX_FACILITY> AUX_FACILITY { get; set; }
        public virtual ICollection<AUX_FACILITY> AUX_FACILITY1 { get; set; }
        public virtual ICollection<AUX_KIT_INSTANCE> AUX_KIT_INSTANCE { get; set; }
        public virtual ICollection<AUX_KIT_INSTANCE> AUX_KIT_INSTANCE1 { get; set; }
        public virtual ICollection<AUX_PRODUCT_ORDER> AUX_PRODUCT_ORDER { get; set; }
        public virtual ICollection<AUX_PRODUCT_ORDER> AUX_PRODUCT_ORDER1 { get; set; }
        public virtual AUX_TERRITORY AUX_TERRITORY { get; set; }
        public virtual ICollection<AUX_USER> AUX_USER { get; set; }
        public virtual ICollection<AUX_USER> AUX_USER1 { get; set; }
    }
}
