//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_CUSTOMER_MASTER
    {
        public int ID { get; set; }
        public string ACCOUNT_NUMBER { get; set; }
        public string CUSTOMER_TYPE { get; set; }
        public string NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string NAME_LCASE { get; set; }
        public string FIRST_NAME_LCASE { get; set; }
        public string MIDDLE_NAME_LCASE { get; set; }
        public string LAST_NAME_LCASE { get; set; }
        public string TERRITORY_NUMBER { get; set; }
        public string TERRITORY_NAME { get; set; }
        public string BILL_TO_NUMBER { get; set; }
        public string BILL_ADDRESS_STREET1 { get; set; }
        public string BILL_ADDRESS_STREET2 { get; set; }
        public string BILL_ADDRESS_CITY { get; set; }
        public string BILL_ADDRESS_STATE { get; set; }
        public string BILL_ADDRESS_POSTAL_CODE { get; set; }
        public string BILL_ADDRESS_COUNTRY { get; set; }
        public string SHIP_TO_NUMBER { get; set; }
        public string SHIP_TO_NAME { get; set; }
        public string SHIP_ADDRESS_STREET1 { get; set; }
        public string SHIP_ADDRESS_STREET2 { get; set; }
        public string SHIP_ADDRESS_CITY { get; set; }
        public string SHIP_ADDRESS_STATE { get; set; }
        public string SHIP_ADDRESS_POSTAL_CODE { get; set; }
        public string SHIP_ADDRESS_COUNTRY { get; set; }
        public short PRIMARY_LOCATION_FLAG { get; set; }
        public string MAIL_TO_NUMBER { get; set; }
        public string MAIL_ADDRESS_STREET1 { get; set; }
        public string MAIL_ADDRESS_STREET2 { get; set; }
        public string MAIL_ADDRESS_CITY { get; set; }
        public string MAIL_ADDRESS_STATE { get; set; }
        public string MAIL_ADDRESS_POSTAL_CODE { get; set; }
        public string MAIL_ADDRESS_COUNTRY { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string FAX_NUMBER { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public short CHANGE_TYPE { get; set; }
        public short IS_IN_FEED { get; set; }
        public short DELETE_FLAG { get; set; }
        public short ERROR_FLAG { get; set; }
        public short REJECTED_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    }
}
