//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_KIT
    {
        public AUX_KIT()
        {
            this.AUX_CASE_PRODUCT = new HashSet<AUX_CASE_PRODUCT>();
            this.AUX_CASE_PRODUCT_AUGMENT = new HashSet<AUX_CASE_PRODUCT_AUGMENT>();
            this.AUX_KIT_IMAGE = new HashSet<AUX_KIT_IMAGE>();
            this.AUX_KIT_CONTENT = new HashSet<AUX_KIT_CONTENT>();
            this.AUX_KIT_INSTANCE = new HashSet<AUX_KIT_INSTANCE>();
            this.AUX_SALES_ORDER_PRODUCT = new HashSet<AUX_SALES_ORDER_PRODUCT>();
            this.AUX_TRUNK_ORDER_PRODUCT = new HashSet<AUX_TRUNK_ORDER_PRODUCT>();
            this.AUX_KIT1 = new HashSet<AUX_KIT>();
            this.AUX_KIT_TEMPLATE_CONTENT = new HashSet<AUX_KIT_TEMPLATE_CONTENT>();
        }
    
        public int ID { get; set; }
        public int LINE_ID { get; set; }
        public Nullable<int> COMPONENT_ID { get; set; }
        public Nullable<int> PARENT_KIT_ID { get; set; }
        public int TERRITORY_ID { get; set; }
        public string KIT_TYPE_LV { get; set; }
        public string KIT_NUMBER { get; set; }
        public string NAME { get; set; }
        public short VERSION_NUM { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<short> DELIVERY_DAYS { get; set; }
        public Nullable<short> RETURN_DAYS { get; set; }
        public short DELETE_FLAG { get; set; }
        public Nullable<System.DateTime> DELETE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<AUX_CASE_PRODUCT> AUX_CASE_PRODUCT { get; set; }
        public virtual ICollection<AUX_CASE_PRODUCT_AUGMENT> AUX_CASE_PRODUCT_AUGMENT { get; set; }
        public virtual ICollection<AUX_KIT_IMAGE> AUX_KIT_IMAGE { get; set; }
        public virtual ICollection<AUX_KIT_CONTENT> AUX_KIT_CONTENT { get; set; }
        public virtual ICollection<AUX_KIT_INSTANCE> AUX_KIT_INSTANCE { get; set; }
        public virtual ICollection<AUX_SALES_ORDER_PRODUCT> AUX_SALES_ORDER_PRODUCT { get; set; }
        public virtual ICollection<AUX_TRUNK_ORDER_PRODUCT> AUX_TRUNK_ORDER_PRODUCT { get; set; }
        public virtual AUX_PRODUCT_LINE AUX_PRODUCT_LINE { get; set; }
        public virtual AUX_PRODUCT_COMPONENT AUX_PRODUCT_COMPONENT { get; set; }
        public virtual ICollection<AUX_KIT> AUX_KIT1 { get; set; }
        public virtual AUX_KIT AUX_KIT2 { get; set; }
        public virtual ICollection<AUX_KIT_TEMPLATE_CONTENT> AUX_KIT_TEMPLATE_CONTENT { get; set; }
        public virtual AUX_TERRITORY AUX_TERRITORY { get; set; }
        public virtual MED_KIT MED_KIT { get; set; }
    }
}
