//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_SURGEON
    {
        public AUX_SURGEON()
        {
            this.AUX_KIT_TEMPLATE_SURGEON = new HashSet<AUX_KIT_TEMPLATE_SURGEON>();
            this.AUX_SURGEON_FACILITY = new HashSet<AUX_SURGEON_FACILITY>();
        }
    
        public int CUSTOMER_ID { get; set; }
        public int CUSTOMER_CONTACT_ID { get; set; }
        public int REGION_ID { get; set; }
        public string GENDER { get; set; }
        public string SPECIALTY { get; set; }
        public string DEA_NUMBER { get; set; }
        public string ME_NUMBER { get; set; }
        public string IMS_NUMBER { get; set; }
        public string OFFICE_HOURS { get; set; }
        public string OR_HOURS { get; set; }
        public string DATA1 { get; set; }
        public string DATA2 { get; set; }
        public string DATA3 { get; set; }
        public short TEST_FLAG { get; set; }
        public string SOURCE { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<AUX_KIT_TEMPLATE_SURGEON> AUX_KIT_TEMPLATE_SURGEON { get; set; }
        public virtual AUX_REGION AUX_REGION { get; set; }
        public virtual ICollection<AUX_SURGEON_FACILITY> AUX_SURGEON_FACILITY { get; set; }
        public virtual PRC_CONTACT PRC_CONTACT { get; set; }
        public virtual PRC_CUSTOMER PRC_CUSTOMER { get; set; }
    }
}
