//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_INVENTORY_TRACK
    {
        public int ID { get; set; }
        public System.DateTime TRANSACTION_DATETIME { get; set; }
        public string TRANSACTION_TYPE_LV { get; set; }
        public int AUX_ID { get; set; }
        public string AUX_TYPE_LV { get; set; }
        public Nullable<int> AUX_LOCATION_ID { get; set; }
        public string AUX_LOCATION_TYPE_LV { get; set; }
        public int PRODUCT_ID { get; set; }
        public string LOT_CODE { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public short AUGMENTED_FLAG { get; set; }
        public Nullable<int> CASE_ID { get; set; }
        public string ADDITIONAL_VALUES_XML { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
    
        public virtual AUX_CASE AUX_CASE { get; set; }
        public virtual AUX_PRODUCT AUX_PRODUCT { get; set; }
    }
}
