//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_PRODUCT_USED
    {
        public int ID { get; set; }
        public int CASE_ID { get; set; }
        public Nullable<int> KIT_INSTANCE_ID { get; set; }
        public string PART_NUMBER { get; set; }
        public string NAME { get; set; }
        public string DISPOSITION_LV { get; set; }
        public string LOT_CODE { get; set; }
        public string LOT_BARCODE { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public short NO_LOT_FLAG { get; set; }
        public int QTY { get; set; }
        public string SOURCE_LOCATION_LV { get; set; }
        public short REPLACE_FLAG { get; set; }
        public string SHIP_ADDRESS_TYPE { get; set; }
        public Nullable<int> SHIP_TO_ADDRESS_ID { get; set; }
        public string SHIP_ATTENTION { get; set; }
        public string SHIP_NOTE { get; set; }
        public string SHIP_TO_METHOD_LV { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string PRICE_TYPE { get; set; }
        public short CAP_FLAG { get; set; }
        public string CAP_CODE { get; set; }
        public string CORP_ORDER_NUM { get; set; }
        public Nullable<System.DateTime> CORP_ORDER_DATE { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual AUX_POST_BILL AUX_POST_BILL { get; set; }
        public virtual AUX_SHIP_TO_ADDRESS AUX_SHIP_TO_ADDRESS { get; set; }
    }
}
