//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_CASE_PRODUCT_CONFLICT
    {
        public int ID { get; set; }
        public int CASE_PRODUCT_ID { get; set; }
        public int CASE_ID { get; set; }
        public Nullable<int> KIT_INSTANCE_ID_PREV { get; set; }
        public Nullable<int> KIT_INSTANCE_ID_PUBL { get; set; }
        public Nullable<int> KIT_INSTANCE_ID_SUBS { get; set; }
        public Nullable<int> KIT_INSTANCE_ID_FINL { get; set; }
        public Nullable<int> NEXT_CASE_ID_PREV { get; set; }
        public Nullable<int> NEXT_CASE_ID_PUBL { get; set; }
        public Nullable<int> NEXT_CASE_ID_SUBS { get; set; }
        public Nullable<int> NEXT_CASE_ID_FINL { get; set; }
        public string STATUS_LV_PREV { get; set; }
        public string STATUS_LV_PUBL { get; set; }
        public string STATUS_LV_SUBS { get; set; }
        public string STATUS_LV_FINL { get; set; }
        public string STATUS { get; set; }
        public string ML_REMOTE_ID { get; set; }
        public string ML_USER_NAME { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual AUX_CASE AUX_CASE { get; set; }
        public virtual AUX_CASE AUX_CASE1 { get; set; }
        public virtual AUX_CASE AUX_CASE2 { get; set; }
        public virtual AUX_CASE AUX_CASE3 { get; set; }
        public virtual AUX_CASE AUX_CASE4 { get; set; }
        public virtual AUX_CASE_PRODUCT AUX_CASE_PRODUCT { get; set; }
        public virtual AUX_KIT_INSTANCE AUX_KIT_INSTANCE { get; set; }
        public virtual AUX_KIT_INSTANCE AUX_KIT_INSTANCE1 { get; set; }
        public virtual AUX_KIT_INSTANCE AUX_KIT_INSTANCE2 { get; set; }
        public virtual AUX_KIT_INSTANCE AUX_KIT_INSTANCE3 { get; set; }
    }
}
