//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_COMPANY
    {
        public AUX_COMPANY()
        {
            this.AUX_TERRITORY = new HashSet<AUX_TERRITORY>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string IDENTIFIER { get; set; }
        public Nullable<System.DateTime> SVR_INSERT_DATETIME { get; set; }
        public Nullable<System.DateTime> SVR_UPDATE_DATETIME { get; set; }
        public Nullable<int> PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<AUX_TERRITORY> AUX_TERRITORY { get; set; }
    }
}
