//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_POST_BILL
    {
        public AUX_POST_BILL()
        {
            this.AUX_PRODUCT_USED = new HashSet<AUX_PRODUCT_USED>();
        }
    
        public int CASE_ID { get; set; }
        public string ORDER_NUMBER { get; set; }
        public short CAP_PROCEDURE { get; set; }
        public string CAP_CODE { get; set; }
        public Nullable<decimal> CAP_PRICE { get; set; }
        public Nullable<decimal> CAP_UPCHARGE { get; set; }
        public short PRICE_FLAG { get; set; }
        public short RUSH_FLAG { get; set; }
        public System.DateTime REPLACE_BY_DATE { get; set; }
        public string NOTE { get; set; }
        public decimal FREIGHT { get; set; }
        public Nullable<decimal> MISC_FEE { get; set; }
        public string SHIP_INSTRUCTION_LV { get; set; }
        public string SIG_BY { get; set; }
        public string SIGNATURE { get; set; }
        public short STATUS { get; set; }
        public string SOURCE { get; set; }
        public Nullable<System.DateTime> WORKED_ON_DATETIME { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual AUX_CASE AUX_CASE { get; set; }
        public virtual ICollection<AUX_PRODUCT_USED> AUX_PRODUCT_USED { get; set; }
        public virtual MED_POST_BILL MED_POST_BILL { get; set; }
    }
}
