//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_PRODUCT_BRAND
    {
        public AUX_PRODUCT_BRAND()
        {
            this.AUX_PRODUCT_COMPONENT = new HashSet<AUX_PRODUCT_COMPONENT>();
        }
    
        public int ID { get; set; }
        public int LINE_ID { get; set; }
        public string LOB_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public short SEQUENCE_NUM { get; set; }
        public short HIDE_FLAG { get; set; }
        public short DELETE_FLAG { get; set; }
        public Nullable<System.DateTime> DELETE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<AUX_PRODUCT_COMPONENT> AUX_PRODUCT_COMPONENT { get; set; }
        public virtual AUX_PRODUCT_LINE AUX_PRODUCT_LINE { get; set; }
    }
}
