//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_SHIP_TO_ADDRESS
    {
        public AUX_SHIP_TO_ADDRESS()
        {
            this.AUX_PRODUCT_ORDER = new HashSet<AUX_PRODUCT_ORDER>();
            this.AUX_PRODUCT_USED = new HashSet<AUX_PRODUCT_USED>();
        }
    
        public int ID { get; set; }
        public string SHIP_TO_TYPE_LV { get; set; }
        public int SHIP_TO_ID { get; set; }
        public int ADDRESS_ID { get; set; }
        public short PRIMARY_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual AUX_ADDRESS AUX_ADDRESS { get; set; }
        public virtual ICollection<AUX_PRODUCT_ORDER> AUX_PRODUCT_ORDER { get; set; }
        public virtual ICollection<AUX_PRODUCT_USED> AUX_PRODUCT_USED { get; set; }
    }
}
