//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_PRODUCT_ORDER_PART
    {
        public int ID { get; set; }
        public int PRODUCT_ORDER_ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public Nullable<int> AUX_ID { get; set; }
        public string AUX_TYPE_LV { get; set; }
        public Nullable<short> SEQUENCE_NUM { get; set; }
        public string TRACKING_NUM { get; set; }
        public string LOT_CODE { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public string PACK_NUM { get; set; }
        public string CUSTOM_IDENTIFIER { get; set; }
        public string REQUEST_STATUS_LV { get; set; }
        public string PROCESS_STATUS_LV { get; set; }
        public short SHIPMENT_COMPLETE_FLAG { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual AUX_PRODUCT AUX_PRODUCT { get; set; }
        public virtual AUX_PRODUCT_ORDER AUX_PRODUCT_ORDER { get; set; }
    }
}
