//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_KIT_TEMPLATE
    {
        public AUX_KIT_TEMPLATE()
        {
            this.AUX_KIT_TEMPLATE_CONTENT = new HashSet<AUX_KIT_TEMPLATE_CONTENT>();
            this.AUX_KIT_TEMPLATE_SURGEON = new HashSet<AUX_KIT_TEMPLATE_SURGEON>();
        }
    
        public int ID { get; set; }
        public int TERRITORY_ID { get; set; }
        public int ACTIVITY_TYPE_ID { get; set; }
        public string NAME { get; set; }
        public string NOTE { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_ACTIVITY_TYPE ADM_ACTIVITY_TYPE { get; set; }
        public virtual ICollection<AUX_KIT_TEMPLATE_CONTENT> AUX_KIT_TEMPLATE_CONTENT { get; set; }
        public virtual ICollection<AUX_KIT_TEMPLATE_SURGEON> AUX_KIT_TEMPLATE_SURGEON { get; set; }
        public virtual AUX_TERRITORY AUX_TERRITORY { get; set; }
    }
}
