//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_USER
    {
        public AUX_USER()
        {
            this.AUX_USER_ADDRESS = new HashSet<AUX_USER_ADDRESS>();
            this.MED_NAMED_FILTERS = new HashSet<MED_NAMED_FILTERS>();
        }
    
        public int USER_ID { get; set; }
        public int REGION_ID { get; set; }
        public int TERRITORY_ID { get; set; }
        public int USER_TYPE_ID { get; set; }
        public int PRIMARY_WAREHOUSE_ID { get; set; }
        public Nullable<int> REP_WAREHOUSE_ID { get; set; }
        public string BILLING_NUMBER { get; set; }
        public short TEST_FLAG { get; set; }
        public short CORP_LOANER_REQUEST_FLAG { get; set; }
        public Nullable<System.DateTime> SVR_INSERT_DATETIME { get; set; }
        public Nullable<System.DateTime> SVR_UPDATE_DATETIME { get; set; }
        public Nullable<int> PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_LIST ADM_LIST { get; set; }
        public virtual ADM_USER ADM_USER { get; set; }
        public virtual AUX_REGION AUX_REGION { get; set; }
        public virtual AUX_TERRITORY AUX_TERRITORY { get; set; }
        public virtual ICollection<AUX_USER_ADDRESS> AUX_USER_ADDRESS { get; set; }
        public virtual ICollection<MED_NAMED_FILTERS> MED_NAMED_FILTERS { get; set; }
        public virtual AUX_WAREHOUSE AUX_WAREHOUSE { get; set; }
        public virtual AUX_WAREHOUSE AUX_WAREHOUSE1 { get; set; }
    }
}
