//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_CAP_CODE
    {
        public int ID { get; set; }
        public Nullable<int> FACILITY_ID { get; set; }
        public Nullable<int> ACTIVITY_TYPE_ID { get; set; }
        public string CAP_CLASS { get; set; }
        public string CAP_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal PRICE { get; set; }
        public short PRIMARY_FLAG { get; set; }
        public short DELETE_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_ACTIVITY_TYPE ADM_ACTIVITY_TYPE { get; set; }
        public virtual AUX_FACILITY AUX_FACILITY { get; set; }
    }
}
