//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_ASN_MASTER
    {
        public int ID { get; set; }
        public string ORDER_NUMBER { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public string SHIP_TO_NUMBER { get; set; }
        public string TERRITORY_NUMBER { get; set; }
        public string PACK_NUM { get; set; }
        public string SHIP_ADDRESS_STREET1 { get; set; }
        public string SHIP_ADDRESS_STREET2 { get; set; }
        public string SHIP_ADDRESS_CITY { get; set; }
        public string SHIP_ADDRESS_STATE { get; set; }
        public string SHIP_ADDRESS_POSTAL_CODE { get; set; }
        public string SHIP_ADDRESS_COUNTRY { get; set; }
        public string SHIP_TRACKING_NUMBER { get; set; }
        public string SHIPMENT_COMPLETE { get; set; }
        public string PART_NUMBER { get; set; }
        public string LOT_CODE { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public int QTY { get; set; }
        public string CUSTOM_IDENTIFIER { get; set; }
        public string OPERATION_TYPE { get; set; }
        public short CHANGE_TYPE { get; set; }
        public short IS_IN_FEED { get; set; }
        public short DELETE_FLAG { get; set; }
        public short ERROR_FLAG { get; set; }
        public short REJECTED_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    }
}
