//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_ADDRESS
    {
        public AUX_ADDRESS()
        {
            this.AUX_SHIP_TO_ADDRESS = new HashSet<AUX_SHIP_TO_ADDRESS>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string IDENTIFIER { get; set; }
        public string ATTENTION { get; set; }
        public string STREET1 { get; set; }
        public string STREET2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTAL_CODE { get; set; }
        public string COUNTRY { get; set; }
        public short DELETE_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<AUX_SHIP_TO_ADDRESS> AUX_SHIP_TO_ADDRESS { get; set; }
    }
}
