//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_CASE_PRODUCT_TRACK
    {
        public int CASE_PRODUCT_ID { get; set; }
        public int ACTION_BY_USER_ID { get; set; }
        public System.DateTime TRACKED_ON_DATETIME { get; set; }
        public string ACTION_TYPE { get; set; }
        public int LOCATION_ID { get; set; }
        public string SIGNED_BY { get; set; }
        public string SIGNATURE { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_USER ADM_USER { get; set; }
        public virtual AUX_CASE_PRODUCT AUX_CASE_PRODUCT { get; set; }
    }
}
