//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXC_ERROR_LOG
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public short APP_DEFINITION_ID { get; set; }
        public string MODULE_CODE { get; set; }
        public string ERROR_CODE { get; set; }
        public string TABLE_NAME { get; set; }
        public string TABLE_KEY { get; set; }
        public string TRACE { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_USER ADM_USER { get; set; }
        public virtual SYS_APP_DEFINITION SYS_APP_DEFINITION { get; set; }
    }
}
