//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXC_MESSAGE_QUEUE
    {
        public int ID { get; set; }
        public int TO_USER_ID { get; set; }
        public string SUBJECT { get; set; }
        public string DESCRIPTION { get; set; }
        public short MESSAGE_STATUS { get; set; }
        public Nullable<System.DateTime> PROCESS_DATETIME { get; set; }
        public string ERROR_CODE { get; set; }
        public string ERROR_TEXT { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_USER ADM_USER { get; set; }
    }
}
