//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSM_FEEDSERVICE_CONFIG
    {
        public FSM_FEEDSERVICE_CONFIG()
        {
            this.FSM_FEEDSERVICE_LOG = new HashSet<FSM_FEEDSERVICE_LOG>();
        }
    
        public int ID { get; set; }
        public string TYPE_LV { get; set; }
        public string NAME { get; set; }
        public short INBOUND_FLAG { get; set; }
        public short ACTIVE_FLAG { get; set; }
        public string PREPROCESSING_STOREDPROC_NAME { get; set; }
        public string PROCESSING_STOREDPROC_NAME { get; set; }
        public string POSTPROCESSING_STOREDPROC_NAME { get; set; }
        public string FILENAME_PREFIX { get; set; }
        public string FILENAME_EXTENSION { get; set; }
        public string ASSEMBLY_FILENAME { get; set; }
        public string ASSEMBLY_TYPENAME { get; set; }
        public short LOG_DBCALLS_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
    
        public virtual ICollection<FSM_FEEDSERVICE_LOG> FSM_FEEDSERVICE_LOG { get; set; }
    }
}
