//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class MED_TRACKER_LOG
    {
        public int ID { get; set; }
        public Nullable<int> OBJECT_ID { get; set; }
        public string BUSINESS_OBJECT { get; set; }
        public string LOG_TYPE { get; set; }
        public string ACTION { get; set; }
        public string STATE { get; set; }
        public string SUBJECT { get; set; }
        public string MSG_BODY { get; set; }
        public short SENT_EMAIL { get; set; }
        public string TO_LINE { get; set; }
        public Nullable<System.DateTime> MOBILE_DATETIME { get; set; }
        public Nullable<System.DateTime> SERVER_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    }
}
