//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class MED_SALES_ORDER
    {
        public int AUX_ID { get; set; }
        public Nullable<int> OWNER_ID { get; set; }
        public int STATUS_ID { get; set; }
        public System.DateTime STATUS_DATETIME { get; set; }
        public string LOB_NUMBER1 { get; set; }
        public string LOB_NUMBER2 { get; set; }
        public Nullable<int> LOCKED_BY_ID { get; set; }
        public Nullable<System.DateTime> LOCKED_DATETIME { get; set; }
        public short CANCEL_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_USER ADM_USER { get; set; }
        public virtual ADM_USER ADM_USER1 { get; set; }
        public virtual AUX_SALES_ORDER AUX_SALES_ORDER { get; set; }
    }
}
