//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class MED_PROCESS_RUN
    {
        public string RUN_NAME { get; set; }
        public System.DateTime RUN_BEGIN_DATETIME { get; set; }
        public Nullable<System.DateTime> RUN_END_DATETIME { get; set; }
        public string STATUS { get; set; }
        public string MESSAGE { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    }
}
