//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class MED_SALES_CALL_DEF
    {
        public MED_SALES_CALL_DEF()
        {
            this.MED_SALES_CALL = new HashSet<MED_SALES_CALL>();
        }
    
        public int VERSION_ID { get; set; }
        public string Q1_LABEL { get; set; }
        public string Q2_LABEL { get; set; }
        public string Q3_LABEL { get; set; }
        public string Q4_LABEL { get; set; }
        public string Q5_LABEL { get; set; }
        public string Q6_LABEL { get; set; }
        public string Q7_LABEL { get; set; }
        public string Q8_LABEL { get; set; }
        public string Q9_LABEL { get; set; }
        public string Q10_LABEL { get; set; }
        public string NOTE1_LABEL { get; set; }
        public string NOTE2_LABEL { get; set; }
        public string NOTE3_LABEL { get; set; }
        public string NOTE4_LABEL { get; set; }
        public string NOTE5_LABEL { get; set; }
        public string NOTE6_LABEL { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<MED_SALES_CALL> MED_SALES_CALL { get; set; }
    }
}
