//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRC_DIARY
    {
        public int ID { get; set; }
        public Nullable<int> TYPE_LIST_ID { get; set; }
        public string SUBJECT { get; set; }
        public string CONTENT { get; set; }
        public int CUSTOMER_ID { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_LIST ADM_LIST { get; set; }
        public virtual ADM_USER ADM_USER { get; set; }
        public virtual PRC_CUSTOMER PRC_CUSTOMER { get; set; }
    }
}
