//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRC_RECURRENCE_MAP
    {
        public int ID { get; set; }
        public int RECURRENCE_DEF_ID { get; set; }
        public int ACTIVITY_ID { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual PRC_ACTIVITY PRC_ACTIVITY { get; set; }
        public virtual PRC_RECURRENCE_DEF PRC_RECURRENCE_DEF { get; set; }
    }
}
