//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRC_CUSTOMER
    {
        public PRC_CUSTOMER()
        {
            this.PRC_ACTION = new HashSet<PRC_ACTION>();
            this.PRC_ACTIVITY = new HashSet<PRC_ACTIVITY>();
            this.PRC_APPOINTMENT = new HashSet<PRC_APPOINTMENT>();
            this.PRC_APPOINTMENT_GROUP = new HashSet<PRC_APPOINTMENT_GROUP>();
            this.PRC_ATTACHMENT = new HashSet<PRC_ATTACHMENT>();
            this.PRC_ATTACHMENT_REFERENCE = new HashSet<PRC_ATTACHMENT_REFERENCE>();
            this.PRC_CUSTOMER_CONTACT = new HashSet<PRC_CUSTOMER_CONTACT>();
            this.PRC_CUSTOMER_DETAIL = new HashSet<PRC_CUSTOMER_DETAIL>();
            this.PRC_DIARY = new HashSet<PRC_DIARY>();
            this.PRC_LINK = new HashSet<PRC_LINK>();
            this.PRC_NOTE = new HashSet<PRC_NOTE>();
            this.PRC_RECURRENCE_ACTIVITY = new HashSet<PRC_RECURRENCE_ACTIVITY>();
        }
    
        public int ID { get; set; }
        public string LOB_NATIVE_IDENTIFIER { get; set; }
        public short CUSTOMER_TYPE { get; set; }
        public short CATEGORY { get; set; }
        public string IDENTIFIER { get; set; }
        public Nullable<int> OWNER_USER_ID { get; set; }
        public string CUSTOM_FIELD_1 { get; set; }
        public string CUSTOM_FIELD_2 { get; set; }
        public string CUSTOM_FIELD_3 { get; set; }
        public string CUSTOM_FIELD_4 { get; set; }
        public string CUSTOM_FIELD_5 { get; set; }
        public string CUSTOM_FIELD_6 { get; set; }
        public string CUSTOM_FIELD_7 { get; set; }
        public string CUSTOM_FIELD_8 { get; set; }
        public short DELETE_FLAG { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_CUSTOMER_CATEGORY ADM_CUSTOMER_CATEGORY { get; set; }
        public virtual ADM_USER ADM_USER { get; set; }
        public virtual AUX_FACILITY AUX_FACILITY { get; set; }
        public virtual AUX_SURGEON AUX_SURGEON { get; set; }
        public virtual ICollection<PRC_ACTION> PRC_ACTION { get; set; }
        public virtual ICollection<PRC_ACTIVITY> PRC_ACTIVITY { get; set; }
        public virtual ICollection<PRC_APPOINTMENT> PRC_APPOINTMENT { get; set; }
        public virtual ICollection<PRC_APPOINTMENT_GROUP> PRC_APPOINTMENT_GROUP { get; set; }
        public virtual ICollection<PRC_ATTACHMENT> PRC_ATTACHMENT { get; set; }
        public virtual ICollection<PRC_ATTACHMENT_REFERENCE> PRC_ATTACHMENT_REFERENCE { get; set; }
        public virtual ICollection<PRC_CUSTOMER_CONTACT> PRC_CUSTOMER_CONTACT { get; set; }
        public virtual ICollection<PRC_CUSTOMER_DETAIL> PRC_CUSTOMER_DETAIL { get; set; }
        public virtual ICollection<PRC_DIARY> PRC_DIARY { get; set; }
        public virtual ICollection<PRC_LINK> PRC_LINK { get; set; }
        public virtual ICollection<PRC_NOTE> PRC_NOTE { get; set; }
        public virtual ICollection<PRC_RECURRENCE_ACTIVITY> PRC_RECURRENCE_ACTIVITY { get; set; }
    }
}
