//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRC_RECURRENCE_DEF
    {
        public PRC_RECURRENCE_DEF()
        {
            this.PRC_RECURRENCE_ACTIVITY = new HashSet<PRC_RECURRENCE_ACTIVITY>();
            this.PRC_RECURRENCE_APPOINTMENT_GROUP = new HashSet<PRC_RECURRENCE_APPOINTMENT_GROUP>();
            this.PRC_RECURRENCE_MAP = new HashSet<PRC_RECURRENCE_MAP>();
        }
    
        public int ID { get; set; }
        public short RECUR_PATTERN { get; set; }
        public string RECUR_DETAIL { get; set; }
        public System.DateTime RECUR_START_DATE { get; set; }
        public Nullable<System.DateTime> RECUR_END_DATETIME { get; set; }
        public short NUMBER_OCCURRENCES { get; set; }
        public short PRE_CREATE_COUNT { get; set; }
        public short RECUR_COUNTDOWN { get; set; }
        public Nullable<System.DateTime> LAST_GENERATED_OCCUR_DATE { get; set; }
        public short DELETE_FLAG { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<PRC_RECURRENCE_ACTIVITY> PRC_RECURRENCE_ACTIVITY { get; set; }
        public virtual ICollection<PRC_RECURRENCE_APPOINTMENT_GROUP> PRC_RECURRENCE_APPOINTMENT_GROUP { get; set; }
        public virtual ICollection<PRC_RECURRENCE_MAP> PRC_RECURRENCE_MAP { get; set; }
    }
}
