//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRC_ACTION
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int ACTION_TYPE_ID { get; set; }
        public Nullable<System.DateTime> START_DATETIME { get; set; }
        public System.DateTime END_DATETIME { get; set; }
        public short STATUS { get; set; }
        public System.DateTime STATUS_CHANGE_DATETIME { get; set; }
        public Nullable<System.DateTime> REMINDER_DATETIME { get; set; }
        public int CUSTOMER_ID { get; set; }
        public Nullable<int> OWNER_USER_ID { get; set; }
        public short SEQUENCE { get; set; }
        public Nullable<int> WORKLOAD { get; set; }
        public short ORIGINATOR { get; set; }
        public short TEMPLATE_STATUS { get; set; }
        public short PRIORITY { get; set; }
        public int ACTIVITY_ID { get; set; }
        public short DELETE_FLAG { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_ACTION_TYPE ADM_ACTION_TYPE { get; set; }
        public virtual ADM_USER ADM_USER { get; set; }
        public virtual PRC_ACTIVITY PRC_ACTIVITY { get; set; }
        public virtual PRC_CUSTOMER PRC_CUSTOMER { get; set; }
    }
}
