//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRC_ACTIVITY
    {
        public PRC_ACTIVITY()
        {
            this.MED_SALES_CALL = new HashSet<MED_SALES_CALL>();
            this.PRC_ACTION = new HashSet<PRC_ACTION>();
            this.PRC_ACTIVITY_DETAIL = new HashSet<PRC_ACTIVITY_DETAIL>();
            this.PRC_APPOINTMENT_GROUP = new HashSet<PRC_APPOINTMENT_GROUP>();
            this.PRC_ATTACHMENT = new HashSet<PRC_ATTACHMENT>();
            this.PRC_ATTACHMENT_REFERENCE = new HashSet<PRC_ATTACHMENT_REFERENCE>();
            this.PRC_LINK = new HashSet<PRC_LINK>();
            this.PRC_NOTE = new HashSet<PRC_NOTE>();
            this.PRC_RECURRENCE_MAP = new HashSet<PRC_RECURRENCE_MAP>();
        }
    
        public int ID { get; set; }
        public string LOB_NATIVE_IDENTIFIER { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int ACTIVITY_TYPE_ID { get; set; }
        public Nullable<System.DateTime> START_DATETIME { get; set; }
        public System.DateTime END_DATETIME { get; set; }
        public short STATUS { get; set; }
        public System.DateTime STATUS_CHANGE_DATETIME { get; set; }
        public Nullable<System.DateTime> REMINDER_DATETIME { get; set; }
        public int CUSTOMER_ID { get; set; }
        public int CONTACT_ID { get; set; }
        public Nullable<int> OWNER_USER_ID { get; set; }
        public Nullable<int> WORKLOAD { get; set; }
        public short ORIGINATOR { get; set; }
        public int SYNC_STATUS { get; set; }
        public short TEMPLATE_STATUS { get; set; }
        public string CUSTOM_FIELD_1 { get; set; }
        public string CUSTOM_FIELD_2 { get; set; }
        public string CUSTOM_FIELD_3 { get; set; }
        public string CUSTOM_FIELD_4 { get; set; }
        public string CUSTOM_FIELD_5 { get; set; }
        public string CUSTOM_FIELD_6 { get; set; }
        public string CUSTOM_FIELD_7 { get; set; }
        public string CUSTOM_FIELD_8 { get; set; }
        public short DELETE_FLAG { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_ACTIVITY_TYPE ADM_ACTIVITY_TYPE { get; set; }
        public virtual ADM_USER ADM_USER { get; set; }
        public virtual AUX_CASE AUX_CASE { get; set; }
        public virtual ICollection<MED_SALES_CALL> MED_SALES_CALL { get; set; }
        public virtual ICollection<PRC_ACTION> PRC_ACTION { get; set; }
        public virtual PRC_CONTACT PRC_CONTACT { get; set; }
        public virtual PRC_CUSTOMER PRC_CUSTOMER { get; set; }
        public virtual ICollection<PRC_ACTIVITY_DETAIL> PRC_ACTIVITY_DETAIL { get; set; }
        public virtual PRC_APPOINTMENT PRC_APPOINTMENT { get; set; }
        public virtual ICollection<PRC_APPOINTMENT_GROUP> PRC_APPOINTMENT_GROUP { get; set; }
        public virtual ICollection<PRC_ATTACHMENT> PRC_ATTACHMENT { get; set; }
        public virtual ICollection<PRC_ATTACHMENT_REFERENCE> PRC_ATTACHMENT_REFERENCE { get; set; }
        public virtual ICollection<PRC_LINK> PRC_LINK { get; set; }
        public virtual ICollection<PRC_NOTE> PRC_NOTE { get; set; }
        public virtual ICollection<PRC_RECURRENCE_MAP> PRC_RECURRENCE_MAP { get; set; }
    }
}
