//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRC_RECURRENCE_ACTIVITY
    {
        public int ID { get; set; }
        public int RECURRENCE_DEF_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public int CONTACT_ID { get; set; }
        public int OWNER_USER_ID { get; set; }
        public int ACTIVITY_TYPE_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string LOCATION { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public System.DateTime END_TIME { get; set; }
        public short DURATION_UNIT { get; set; }
        public short DURATION_UNIT_TYPE { get; set; }
        public short REMINDER_UNIT { get; set; }
        public short REMINDER_UNIT_TYPE { get; set; }
        public string CUSTOM_FIELD_1 { get; set; }
        public string CUSTOM_FIELD_2 { get; set; }
        public string CUSTOM_FIELD_3 { get; set; }
        public string CUSTOM_FIELD_4 { get; set; }
        public string CUSTOM_FIELD_5 { get; set; }
        public string CUSTOM_FIELD_6 { get; set; }
        public string CUSTOM_FIELD_7 { get; set; }
        public string CUSTOM_FIELD_8 { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ADM_ACTIVITY_TYPE ADM_ACTIVITY_TYPE { get; set; }
        public virtual ADM_USER ADM_USER { get; set; }
        public virtual PRC_CONTACT PRC_CONTACT { get; set; }
        public virtual PRC_CUSTOMER PRC_CUSTOMER { get; set; }
        public virtual PRC_RECURRENCE_DEF PRC_RECURRENCE_DEF { get; set; }
    }
}
