//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_LIST_TYPE
    {
        public SYS_LIST_TYPE()
        {
            this.ADM_LIST = new HashSet<ADM_LIST>();
            this.ADM_LIST_LOCALIZED = new HashSet<ADM_LIST_LOCALIZED>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public int MAX_LENGTH { get; set; }
        public short USAGE { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<ADM_LIST> ADM_LIST { get; set; }
        public virtual ICollection<ADM_LIST_LOCALIZED> ADM_LIST_LOCALIZED { get; set; }
    }
}
