//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_WEB_STORED_PROC
    {
        public SYS_WEB_STORED_PROC()
        {
            this.SYS_WEB_SP_PARAMETER = new HashSet<SYS_WEB_SP_PARAMETER>();
        }
    
        public int ID { get; set; }
        public string TAG_USED_BY { get; set; }
        public string TAG_CODE { get; set; }
        public string NAME { get; set; }
        public string STORED_PROC_NAME { get; set; }
        public short HAS_RTN_VALUE { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public Nullable<int> PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<SYS_WEB_SP_PARAMETER> SYS_WEB_SP_PARAMETER { get; set; }
    }
}
