//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_WEB_SP_PARAMETER
    {
        public int ID { get; set; }
        public int STORED_PROC_ID { get; set; }
        public string NAME { get; set; }
        public string PARAMETER { get; set; }
        public string DB_DATA_TYPE { get; set; }
        public string WEB_LABEL_CONTROL_ID { get; set; }
        public string WEB_CONTROL_ID { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual SYS_WEB_STORED_PROC SYS_WEB_STORED_PROC { get; set; }
    }
}
