//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_WEB_CONFIG
    {
        public SYS_WEB_CONFIG()
        {
            this.ADM_WEB_CONFIG = new HashSet<ADM_WEB_CONFIG>();
        }
    
        public short APP_ID { get; set; }
        public string TAG_CODE { get; set; }
        public string VALUE { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<ADM_WEB_CONFIG> ADM_WEB_CONFIG { get; set; }
        public virtual SYS_APP_DEFINITION SYS_APP_DEFINITION { get; set; }
    }
}
