//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_APP_FUNCTION
    {
        public SYS_APP_FUNCTION()
        {
            this.ADM_FUNCTION_ACCESS = new HashSet<ADM_FUNCTION_ACCESS>();
        }
    
        public string CODE { get; set; }
        public short APP_DEFINITION_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string FUNCTION_GROUP { get; set; }
        public short GROUP_ORDER { get; set; }
        public short GROUP_LEVEL { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<ADM_FUNCTION_ACCESS> ADM_FUNCTION_ACCESS { get; set; }
        public virtual SYS_APP_DEFINITION SYS_APP_DEFINITION { get; set; }
    }
}
