//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_LOB
    {
        public SYS_LOB()
        {
            this.ADM_ACTION_TYPE = new HashSet<ADM_ACTION_TYPE>();
            this.ADM_ACTION_TYPE_LOCALIZED = new HashSet<ADM_ACTION_TYPE_LOCALIZED>();
            this.ADM_ACTIVITY_TYPE = new HashSet<ADM_ACTIVITY_TYPE>();
            this.ADM_ACTIVITY_TYPE_LOCALIZED = new HashSet<ADM_ACTIVITY_TYPE_LOCALIZED>();
            this.ADM_CONTENT_TYPE = new HashSet<ADM_CONTENT_TYPE>();
            this.ADM_CONTENT_TYPE_LOCALIZED = new HashSet<ADM_CONTENT_TYPE_LOCALIZED>();
            this.ADM_LINK = new HashSet<ADM_LINK>();
            this.ADM_LINK_LOCALIZED = new HashSet<ADM_LINK_LOCALIZED>();
            this.SYS_LOB_LOCALIZED = new HashSet<SYS_LOB_LOCALIZED>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SYS_CODE { get; set; }
        public System.DateTime EFFECTIVE_DATETIME { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual ICollection<ADM_ACTION_TYPE> ADM_ACTION_TYPE { get; set; }
        public virtual ICollection<ADM_ACTION_TYPE_LOCALIZED> ADM_ACTION_TYPE_LOCALIZED { get; set; }
        public virtual ICollection<ADM_ACTIVITY_TYPE> ADM_ACTIVITY_TYPE { get; set; }
        public virtual ICollection<ADM_ACTIVITY_TYPE_LOCALIZED> ADM_ACTIVITY_TYPE_LOCALIZED { get; set; }
        public virtual ICollection<ADM_CONTENT_TYPE> ADM_CONTENT_TYPE { get; set; }
        public virtual ICollection<ADM_CONTENT_TYPE_LOCALIZED> ADM_CONTENT_TYPE_LOCALIZED { get; set; }
        public virtual ICollection<ADM_LINK> ADM_LINK { get; set; }
        public virtual ICollection<ADM_LINK_LOCALIZED> ADM_LINK_LOCALIZED { get; set; }
        public virtual ICollection<SYS_LOB_LOCALIZED> SYS_LOB_LOCALIZED { get; set; }
    }
}
