//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSM_WEBSERVICE_QUEUE
    {
        public int ID { get; set; }
        public string REQUEST_TYPE_LV { get; set; }
        public string TYPE_LV { get; set; }
        public int TYPE_ID { get; set; }
        public string STATUS_LV { get; set; }
        public int INITIATED_USER_ID { get; set; }
        public Nullable<int> WEBSERVICE_LOG_ID { get; set; }
        public Nullable<int> RETRY_COUNT { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public System.DateTime UPDATE_DATETIME { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
        public System.DateTime LAST_TOUCH_DATETIME { get; set; }
        public System.DateTime ACTIVATION_DATETIME { get; set; }
    
        public virtual WSM_WEBSERVICE_LOG WSM_WEBSERVICE_LOG { get; set; }
    }
}
