//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSM_WEBSERVICE_CONFIG
    {
        public WSM_WEBSERVICE_CONFIG()
        {
            this.WSM_WEBSERVICE_LOG = new HashSet<WSM_WEBSERVICE_LOG>();
        }
    
        public int ID { get; set; }
        public string REQUEST_TYPE_LV { get; set; }
        public string NAME { get; set; }
        public string ENDPOINT_ADDRESS { get; set; }
        public string BINDING_INFO { get; set; }
        public short ACTIVE_FLAG { get; set; }
        public string SERVICE_CHANNEL { get; set; }
        public string SERVICE_NAME { get; set; }
        public decimal VERSION { get; set; }
        public string XSD { get; set; }
        public string INPUT_TRANSFORM { get; set; }
        public string OUTPUT_TRANSFORM { get; set; }
        public string USER_USERNAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public Nullable<System.DateTime> START_DATETIME { get; set; }
        public string ACTION_NAME { get; set; }
        public int UPDATE_BY_USER_ID { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public System.DateTime SVR_UPDATE_DATETIME { get; set; }
    
        public virtual ICollection<WSM_WEBSERVICE_LOG> WSM_WEBSERVICE_LOG { get; set; }
    }
}
