//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSM_WEBSERVICE_LOG
    {
        public WSM_WEBSERVICE_LOG()
        {
            this.WSM_WEBSERVICE_QUEUE = new HashSet<WSM_WEBSERVICE_QUEUE>();
        }
    
        public int ID { get; set; }
        public int CONFIG_ID { get; set; }
        public string REQUEST { get; set; }
        public string RESPONSE { get; set; }
        public Nullable<System.DateTime> TOTAL_EXECUTION_TIME { get; set; }
        public string LOG_TYPE { get; set; }
        public Nullable<short> RESULT { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime SVR_INSERT_DATETIME { get; set; }
        public Nullable<System.DateTime> SVR_UPDATE_DATETIME { get; set; }
        public int PERFORM_BY_USER_ID { get; set; }
    
        public virtual WSM_WEBSERVICE_CONFIG WSM_WEBSERVICE_CONFIG { get; set; }
        public virtual ICollection<WSM_WEBSERVICE_QUEUE> WSM_WEBSERVICE_QUEUE { get; set; }
    }
}
