//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMvcApplication8
{
    using System;
    
    public partial class xpmed_PostBillDetails_DetailResult
    {
        public string Confirmed { get; set; }
        public string PartNumber { get; set; }
        public string Name { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PriceType { get; set; }
        public string LotNumber { get; set; }
        public string SourceLocation { get; set; }
        public string Status { get; set; }
        public short ConfirmRequired { get; set; }
        public string ShipAddressType { get; set; }
        public Nullable<int> ShipAddressId { get; set; }
        public string ShipAttention { get; set; }
        public string ShipNote { get; set; }
        public Nullable<System.DateTime> ConfirmedDT { get; set; }
        public string ConfirmedBy { get; set; }
        public int Id { get; set; }
        public int CaseId { get; set; }
        public short LiveFlag { get; set; }
        public short LotRequired { get; set; }
        public string SourceLocValue { get; set; }
        public string NextFacility { get; set; }
        public string PartShipToType { get; set; }
        public string PartShipToNumber { get; set; }
        public string PartShipToMethod { get; set; }
        public string AccountPrice { get; set; }
        public int KitInstanceId { get; set; }
        public string KitInstanceName { get; set; }
        public string KitSerialNumber { get; set; }
        public int CurrentWarehouseId { get; set; }
        public string CurrentWarehouse { get; set; }
        public int CurrentWHShipToId { get; set; }
        public string Location { get; set; }
        public short CAPFlag { get; set; }
        public string CapCode { get; set; }
        public string SalesUOM { get; set; }
        public int ProductId { get; set; }
        public string LotBarCode { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string PartCategory { get; set; }
        public string ReplenishmentOrderNumber { get; set; }
        public Nullable<System.DateTime> ReplenishmentOrderDate { get; set; }
        public short KitFlag { get; set; }
        public int AugmentPartsQty { get; set; }
        public string DefaultWareHouseShipAddressIDShipToNumber { get; set; }
        public string DefaultFacilityShipAddressIDShipToNumber { get; set; }
        public string DefaultUserShipAddressIDShipToNumber { get; set; }
    }
}
